services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
      restart: "no"
      ports:
        - "8000:8000"
      command:
        - uv
        - run
        - uvicorn
        - app.main:app
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        - --reload
      volumes:
        - ./backend/app:/app/app:z
      environment:
        - ENVIRONMENT=local
        - PYTHONPATH=/app
  prometheus:
    image: prom/prometheus:latest
    restart: "no"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - ./monitoring/rules.yml:/etc/prometheus/rules.yml:z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager:latest
    restart: "no"
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:z
      - ./monitoring/token.txt:/etc/alertmanager/token.txt:z
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
