global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
  receiver: alertflow

receivers:
  - name: alertflow
    webhook_configs:
      - url: 'http://backend:8000/api/v1/webhooks/prometheus'
        send_resolved: false
        http_config:
          authorization:
            type: Bearer
            credentials_file: /etc/alertmanager/token.txt
